tags/urls.py
from django.urls import path
from . import views
from .followers import views as tagfollowers_views

app_name = 'tags'

urlpatterns = [
  path('', views.TagViews.as_view(), name="TagList"),
  path('<int:id>', views.TagDetailViews.as_view(), name="TagDetails"),
  path('<int:id>/followers', tagfollowers_views.TagFollowersView.as_view(), name='ManageTagFollower'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', home, name='home'),
  path('users/', include('users.urls')),
  path('tweets/', include('tweets.urls')),
  path('tags/', include('tags.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tags/followers/models.py
from django.db import models
from users.models import User
# Create your models here.




class tagsFollowers(models.Model):
  tag = models.ForeignKey('tags.Tag',on_delete=models.CASCADE)
  user = models.ForeignKey(User,on_delete=models.CASCADE)

  class Meta:
    constraints = [
      models.UniqueConstraint(fields=['tag', 'user'], name='unique_user_tag_follow')
    ]

tags/models.py
from django.db import models
from tags.followers.models import tagsFollowers
# Create your models here.

class Tag(models.Model):
  name = models.CharField(max_length=160)

tags/followers/views.py
from django.shortcuts import  get_object_or_404
from tags.models import Tag
from django.contrib import messages
from django.views import View
from django.http import JsonResponse
from tags.followers.models import tagsFollowers
# Create your views here.

class TagFollowersView(View):
  def post(self, request, id):
    tag = get_object_or_404(Tag, id=id)
    tagsFollowers.objects.create(user=request.user, tag=tag)
    messages.success(request, "Following Tag now")
    return JsonResponse({'status': 200})

  def delete(self, request, id):
    tag_following = get_object_or_404(tagsFollowers, tag_id=id, user_id=request.user.id)
    tag_following.delete()
    messages.success(request, "Unfollowing now")
    return JsonResponse({'status': 200})

tags/views.py
from django.shortcuts import render, get_object_or_404
from .models import Tag
from django.views import View
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage

# Create your views here.
class TagViews(View):
  def get(self,request):
    all_tags = Tag.objects.all().order_by('-id')
    page = request.GET.get('page', 1)
    limit = request.GET.get('limit', 5)
    paginator = Paginator(all_tags, limit)
    try:
      tags = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
      tags = paginator.page(1)
    return render(request,'tags/list.html', {'all_tags': tags})

class TagDetailViews(View):
  def get(self,request,id):
    tag = get_object_or_404(Tag, id=id)
    return render(request, 'tags/show.html',{'tag':tag})

templates/tags/list.html
{% extends "includes/base.html" %}
{% block main_content %}

<div>
  <h4>All Tags</h4>
  {% for tag in all_tags %}
  <div>
    <a href="{% url 'tags:TagDetails' tag.id %}">
      <h6>{{ tag.name }}</h6>
    </a>
  </div>
  {% endfor %}
  <div>
    {% if all_tags.paginator.num_pages > 1 %}
      <ul class="pagination">
        {% if all_tags.has_previous %}
          <li><a href="?page={{ all_tags.previous_page_number }}&limit=5">Previous</a></li>
        {% endif %}
        <li><a href="#" class="active">{{ all_tags.number }}</a> </li>
        {% if all_tags.has_next %}
          <li><a href="?page={{ all_tags.next_page_number }}&limit=5">Next</a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

templates/tags/show.html
{% extends "includes/base.html" %}
{% block main_content %}
{% load tagfollower_tags %}
<div>
  <h4>Tag Details</h4>
  <div>
    <h6>{{ tag.name }}</h6>
    {% if request.user.is_authenticated and not request.user|is_following_tag:tag %}
      <form id="tagFollowRequestForm">
        <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'tags:ManageTagFollower' tag.id %}','POST','tagFollowRequestForm')">Follow</a>
      </form>
    {% elif request.user.is_authenticated and request.user|is_following_tag:tag %}
      <form id="tagUnfollowRequestForm">
        <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'tags:ManageTagFollower' tag.id %}','DELETE','tagUnfollowRequestForm')">Unfollow</a>
      </form>
    {% endif %}
  </div>
{% endblock %}