tags/urls.py
from django.urls import path
from . import views
from .followers import views as tagfollowers_views

app_name = 'tags'

urlpatterns = [
  path('', views.TagViews.as_view(), name="TagList"),
  path('<int:id>', views.TagDetailViews.as_view(), name="TagDetails"),
  path('<int:id>/followers', tagfollowers_views.TagFollowersView.as_view(), name='ManageTagFollower'),
]

tweets/urls.py
from django.urls import path
from . import views as tweets_views
from .retweets import views as retweets_views
from .likes import views as likes_views
app_name = 'tweets'

urlpatterns = [
  path('', tweets_views.TweetsViews.as_view(), name='ListCreateTweets'),
  path('<int:id>', tweets_views.TweetDetailViews.as_view(), name='ManageTweet'),
  path('<int:id>/edit', tweets_views.TweetDetailViews.as_view(), {'action': 'edit'}, name='editTweet'),
  path('<int:original_tweet_id>/retweet/', retweets_views.RetweetView.as_view(http_method_names=['post']), name='reTweet'),
  path('<int:id>/likes', likes_views.LikesView.as_view(), name='LikeTweet'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', home, name='home'),
  path('users/', include('users.urls')),
  path('tweets/', include('tweets.urls')),
  path('tags/', include('tags.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from .followers import views as followers_views

app_name = 'users'

urlpatterns = [
  path('<int:id>', views.UserViews.as_view(), name="UserDetails"),
  path('<int:id>/followers', followers_views.FollowersViews.as_view(), name='ManageFollower'),
  path('registrations/new', views.newRegistration, name='newRegistration'),
  path('registrations/create', views.createRegistration, name='createRegistration'),
  path('sessions/new', views.newSession, name='newSession'),
  path('sessions/create', views.createSession, name='createSession'),
  path('logout', views.user_logout, name='Logout'),
]

templates/home.html
{% extends "includes/base.html" %}
{% block main_content %}
{% load tweet_tags %}
{% if request.user.is_authenticated %}
  <div>
    <h4>Add a Tweet</h4>
    <form method="post" action="{% url 'tweets:ListCreateTweets' %}">
      {% csrf_token %}
      <div>
        <label>Tweet</label>
        <textarea
          type="text"
          name="tweet_message"
          rows="4"
          cols="90"
          maxlength="160"
          style="resize: none"
          placeholder="Share what's in your mind (max characters 160)"
          required
        ></textarea>
      </div>
      <div>
        <input type="submit" value="Save" />
      </div>
    </form>
    <a href="{% url 'users:Logout' %}" style="float: right">Logout</a>
  </div>
{% else %}
  <a href="{% url 'users:newSession' %}" style="float: right">Login</a>
{% endif %}
<div>
  <h4>All Tweets</h4>
  {% for tweet in all_tweets %}
  <div class="tweet">
    <a href="{% url 'users:UserDetails' tweet.user.id %}">
      <h6>{{ tweet.user.first_name }}</h6>
    </a>
    {% if tweet.last_edited_at %}
      <p>edited</p>
    {% endif %}
    {% if tweet.original_tweet_id is None %}
      <p>{{ tweet.tweet_message }}</p>
    {% else %}
      <p>Retweeted</p>
      <a href="{% url 'users:UserDetails' tweet.original_tweet.user.id %}">
        <h6>{{ tweet.original_tweet.user.first_name }}</h6>
      </a>
      <p>{{ tweet.original_tweet.tweet_message }}</p>
    {% endif %}

    {% if request.user.id and request.user|can_like:tweet %}
      <form id="LikeRequestForm">
        <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'tweets:LikeTweet' tweet.id %}','POST','LikeRequestForm')">Like</a>
      </form>
    {% elif request.user.id and not request.user|can_like:tweet %}
      <form id="unLikeRequestForm">
        <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'tweets:LikeTweet' tweet.id %}','DELETE','unLikeRequestForm')">UnLike</a>
      </form>
    {% endif %}


    <a href="{% url 'tweets:ManageTweet' tweet.id %}">Show Tweet</a>
    {% if request.user|can_edit_tweet:tweet %}
      <a href="{% url 'tweets:editTweet' tweet.id %}" style="margin-left: 20px;">Edit Tweet</a>
    {% endif %}
    {% if request.user|can_delete_tweet:tweet %}
      <form id="deleteTweetForm" style="display: inline;">
        <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'tweets:ManageTweet' tweet.id %}','DELETE','deleteTweetForm')" style="float: right">Delete Tweet</a>
      </form>
    {% endif %}
    {% if request.user|can_retweet:tweet %}
      <form method="post" action="{% url 'tweets:reTweet' original_tweet_id=tweet.id %}" style="display: inline;">
        {% csrf_token %}
        <button type="submit" style="margin-left: 20px;">Retweet</button>
      </form>
    {% endif %}
  </div>
  {% endfor %}
</div>
<div>
  {% if all_tweets.paginator.num_pages > 1 %}
    <ul class="pagination">
      {% if all_tweets.has_previous %}
        <li><a href="?page={{ all_tweets.previous_page_number }}&limit=5">Previous</a></li>
      {% endif %}
      <li><a href="#" class="active">{{ all_tweets.number }}</a> </li>
      {% if all_tweets.has_next %}
        <li><a href="?page={{ all_tweets.next_page_number }}&limit=5">Next</a></li>
      {% endif %}
    </ul>
  {% endif %}
</div>
{% endblock %}