tags/urls.py
from django.urls import path
from . import views
from .followers import views as tagfollowers_views

app_name = 'tags'

urlpatterns = [
  path('', views.TagViews.as_view(), name="TagList"),
  path('<int:id>', views.TagDetailViews.as_view(), name="TagDetails"),
  path('<int:id>/followers', tagfollowers_views.TagFollowersView.as_view(), name='ManageTagFollower'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', home, name='home'),
  path('users/', include('users.urls')),
  path('tweets/', include('tweets.urls')),
  path('tags/', include('tags.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
  path('<int:id>', views.UserViews.as_view(), name="UserDetails"),
  path('registrations/new', views.newRegistration, name='newRegistration'),
  path('registrations/create', views.createRegistration, name='createRegistration'),
  path('sessions/new', views.newSession, name='newSession'),
  path('sessions/create', views.createSession, name='createSession'),
  path('logout', views.user_logout, name='Logout'),
]

users/urls.py
from django.urls import path
from . import views
from .followers import views as followers_views

app_name = 'users'

urlpatterns = [
  path('<int:id>', views.UserViews.as_view(), name="UserDetails"),
  path('<int:id>/followers', followers_views.FollowersViews.as_view(), name='ManageFollower'),
  path('registrations/new', views.newRegistration, name='newRegistration'),
  path('registrations/create', views.createRegistration, name='createRegistration'),
  path('sessions/new', views.newSession, name='newSession'),
  path('sessions/create', views.createSession, name='createSession'),
  path('logout', views.user_logout, name='Logout'),
]

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
  email = models.CharField(max_length=254, unique=True)
  followers =models.ManyToManyField('user.User')

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
  email = models.CharField(max_length=254, unique=True)
  followers =models.ManyToManyField('users.User')

users/followers/views.py
from django.shortcuts import get_object_or_404
from users.models import User
from django.contrib import messages
from django.views import View
from django.http import JsonResponse
import json


class FollowersViews(View):
  def post(self, request, id):
    follow_to_user = get_object_or_404(User, id=id)
    if request.user.id==id:
      messages.error(request,'Cannot follow yourself')
      return JsonResponse({'status': 422})
    if request.user.id in follow_to_user.followers.all():
      messages.error(request,'You are already following')
      return JsonResponse({'status': 422})
    follow_to_user.followers.add(request.user.id)
    messages.success(request, "Following now")
    return JsonResponse({'status': 200})

  def delete(self, request, id):
    unfollow_to_user = get_object_or_404(User, id=id)
    if request.user.id==id:
      messages.error(request,'Cannot unfollow yourself')
      return JsonResponse({'status': 422})
    if not unfollow_to_user.followers.filter(id=request.user.id).exists():
      messages.error(request,'You are not following')
      return JsonResponse({'status': 422})
    unfollow_to_user.followers.remove(request.user.id)
    messages.success(request, "Unfollowing now")
    return JsonResponse({'status': 200})

users/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User
from django.http import Http404
from tweets.models import Tweet
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views import View


def home(request):
  all_tweets = Tweet.objects.all().order_by('-id')
  page = request.GET.get('page', 1)
  limit = request.GET.get('limit', 5)
  paginator = Paginator(all_tweets, limit)
  try:
    tweets = paginator.page(page)
  except (PageNotAnInteger, EmptyPage):
    tweets = paginator.page(1)
  return render(request,'home.html', {'all_tweets': tweets})

class UserViews(View):
  def get(self, request, id):
    user = get_object_or_404(User, id=id)
    return render(request, 'users/show.html',{'user':user})

def newRegistration(request):
  if request.user.is_authenticated:
    return redirect('home')
  return render(request,'users/register.html')

def createRegistration(request):
  if request.method != 'POST':
    raise Http404("Page not found")
  if request.user.is_authenticated:
    return redirect('home')
  email = request.POST.get('email')
  username = email.split("@")[0]
  first_name = request.POST.get('first_name')
  last_name = request.POST.get('last_name')
  password = make_password(request.POST.get('password'))
  try:
    User.objects.create(username=username, password=password, first_name=first_name, last_name=last_name, email=email)
    messages.success(request, "Login to continue")
  except Exception as e:
    messages.error(request, e)
  return redirect('home')

def newSession(request):
  if request.user.is_authenticated:
    return redirect('home')
  return render(request,'users/login.html')

def createSession(request):
  if request.method != 'POST':
    raise Http404("Page not found")
  if request.user.is_authenticated:
    return redirect('home')
  email = request.POST.get('email')
  username = email.split("@")[0]
  password = request.POST.get('password')
  select_user = User.objects.filter(username=username)

  if not select_user:
    messages.warning(request, "Account not found")
    return redirect('home')

  user = authenticate(request,username=username,password=password)
  if not user:
    messages.error(request, "Incorrect password!!!")
    return redirect('home')

  login(request, user)
  return redirect('home')

def user_logout(request):
  logout(request)
  return redirect('home')

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Twitter</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="screen_50">
          <img
            src="{% static 'image/twitter_logo.png' %}"
            alt="Twitter Image Failed to load"
            width="350"
            height="268"
          />
        </div>
        <div class="screen_50">
          <h1>Login</h1>
          <h4>Already have an account.</h4>
          <form method="post" action="{% url 'users:createSession' %}">
            {% csrf_token %}
            <div>
              <label>Email</label>
              <input type="email" name="email" required />
            </div>
            <div>
              <label>Password</label>
              <input type="password" name="password" required />
            </div>
            <div>
              <input type="submit" value="Login" />
            </div>
            <a href="{% url 'users:newRegistration' %}">Register</a>
          </form>
        </div>
      </div>
    </div>
    {% if messages %}
      {% for message in messages %}
        {{message}}
      {% endfor %}
    {% endif %}
  </body>
</html>

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Twitter</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="screen_50">
          <img
            src="{% static 'image/twitter_logo.png' %}"
            alt="Twitter Image Failed to load"
            width="350"
            height="268"
          />
        </div>
        <div class="screen_50">
          <h1>Register</h1>
          <h4>Join Today.</h4>
          <form
            method="post"
            action="{% url 'users:createRegistration' %}"
          >
            {% csrf_token %}
            <div>
              <label>First Name</label>
              <input type="text" name="first_name" required />
            </div>
            <div>
              <label>Last Name</label>
              <input type="text" name="last_name" required />
            </div>
            <div>
              <label>Email</label>
              <input type="email" name="email" required />
            </div>
            <div>
              <label>Password</label>
              <input type="password" name="password" required />
            </div>
            <div>
              <input type="submit" value="Register" />
            </div>
            <a href="{% url 'users:newSession' %}">Login</a>
          </form>
        </div>
      </div>
    </div>
    {% if messages %}
      {% for message in messages %}
        {{message}}
      {% endfor %}
    {% endif %}
  </body>
</html>

templates/users/show.html
{% extends "includes/base.html" %}
{% load follower_tags %}
{% block main_content %}
<a href="{% url 'home' %}" style="float: right">Home</a>
<h4>User Details</h4>
<div>
  <h6>First Name - {{ user.first_name }}</h6>
  <h6>Last Name - {{ user.last_name }}</h6>
  <h6>Followers - {{ user.followers.count }}</h6>
  {% if request.user.id != user.id and not request.user|is_following:user %}
    <form id="followRequestForm">
      <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'users:ManageFollower' user.id %}','POST','followRequestForm')">Follow</a>
    </form>
  {% elif request.user.id != user.id and request.user|is_following:user %}
    <form id="unfollowRequestForm">
      <a href="javascript:void(0)" onclick="asyncFormSubmission('{% url 'users:ManageFollower' user.id %}','DELETE','unfollowRequestForm')">Unfollow</a>
    </form>
  {% endif %}
</div>
{% endblock %}